export const RULES = {
  categories: {
    Billing: [
      "billing",
      "invoice",
      "payment",
      "charge",
      "charged",
      "refund",
      "subscription",
      "refunds",
    ],
    Technical: [
      "error",
      "bug",
      "crash",
      "broken",
      "timeout",
      "latency",
      "down",
      "outage",
      "issue",
      "fail",
      "cannot",
      "degraded",
    ],
    Account: [
      "login",
      "log in",
      "password",
      "sign in",
      "account",
      "locked",
      "verify",
      "verification",
      "2fa",
    ],
    "Feature Request": ["feature", "enhancement", "improve", "request", "wishlist", "idea"],
  },

  // Used for urgency detection (any match => urgent flag).
  urgencyKeywords: ["urgent", "asap", "immediately", "critical", "down", "outage", "production down"],

  // Used for priority scoring.
  severityKeywords: {
    P0: ["security", "breach", "data loss", "outage", "system down", "production down"],
    P1: ["urgent", "asap", "blocked", "cannot login", "payment failed", "major outage", "security"],
    P2: ["error", "issue", "timeout", "broken", "degraded", "intermittent", "slow"],
    P3: ["question", "minor", "feature", "nice to have", "suggestion", "how to"],
  },

  stopWords: new Set([
    "the",
    "a",
    "an",
    "and",
    "or",
    "to",
    "is",
    "are",
    "of",
    "in",
    "for",
    "with",
    "on",
    "this",
    "that",
    "it",
    "we",
    "our",
    "you",
    "your",
    "be",
    "as",
    "at",
    "from",
    "by",
    "please",
    "help",
    "customer",
    "ticket",
  ]),
};

